name: Testezinho

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy data
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '18.x'
      
      - name: Release
        uses: docker://semanticrelease/semantic-release:16
        with:
          args: |
            --branches main
            --debug
            --plugin @semantic-release/git
            --plugin @semantic-release/github
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}
