name: Testezinho

on:
  push:
    branches:
      - main

jobs:
  build:

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Copy data
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}

      - name: Set version env var
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo $VERSION


      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: lamequesao/imagem-teste:${{ github.ref }}
