name: Testezinho develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy data
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set env
        run: |
          echo "NOW=$(date +'%Y.%m.%dT%H.%M.%S')" >> $GITHUB_ENV
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            lamequesao/imagem-teste:latest-${{ env.VERSION }}-${{ env.NOW }}
            lamequesao/imagem-teste:latest
